// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pch_absolute_risk
NumericVector pch_absolute_risk(IntegerVector id, NumericVector dt, NumericMatrix haz, int cause_idx, const bool one_based, const bool na_is_zero);
RcppExport SEXP _tmlensemble_pch_absolute_risk(SEXP idSEXP, SEXP dtSEXP, SEXP hazSEXP, SEXP cause_idxSEXP, SEXP one_basedSEXP, SEXP na_is_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type haz(hazSEXP);
    Rcpp::traits::input_parameter< int >::type cause_idx(cause_idxSEXP);
    Rcpp::traits::input_parameter< const bool >::type one_based(one_basedSEXP);
    Rcpp::traits::input_parameter< const bool >::type na_is_zero(na_is_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(pch_absolute_risk(id, dt, haz, cause_idx, one_based, na_is_zero));
    return rcpp_result_gen;
END_RCPP
}
// pch_survival
NumericVector pch_survival(IntegerVector id, NumericVector dt, NumericMatrix haz, const bool na_is_zero);
RcppExport SEXP _tmlensemble_pch_survival(SEXP idSEXP, SEXP dtSEXP, SEXP hazSEXP, SEXP na_is_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type haz(hazSEXP);
    Rcpp::traits::input_parameter< const bool >::type na_is_zero(na_is_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(pch_survival(id, dt, haz, na_is_zero));
    return rcpp_result_gen;
END_RCPP
}
// poisson_deviance_cpp
DataFrame poisson_deviance_cpp(IntegerVector folder, CharacterVector learner, NumericMatrix lambda, NumericVector tij, IntegerMatrix delta);
RcppExport SEXP _tmlensemble_poisson_deviance_cpp(SEXP folderSEXP, SEXP learnerSEXP, SEXP lambdaSEXP, SEXP tijSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type folder(folderSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type learner(learnerSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tij(tijSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(poisson_deviance_cpp(folder, learner, lambda, tij, delta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tmlensemble_pch_absolute_risk", (DL_FUNC) &_tmlensemble_pch_absolute_risk, 6},
    {"_tmlensemble_pch_survival", (DL_FUNC) &_tmlensemble_pch_survival, 4},
    {"_tmlensemble_poisson_deviance_cpp", (DL_FUNC) &_tmlensemble_poisson_deviance_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_tmlensemble(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
