# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pch_absolute_risk <- function(id, dt, haz, cause_idx, one_based = TRUE, na_is_zero = FALSE) {
    .Call(`_tmlensemble_pch_absolute_risk`, id, dt, haz, cause_idx, one_based, na_is_zero)
}

pch_survival <- function(id, dt, haz, na_is_zero = FALSE) {
    .Call(`_tmlensemble_pch_survival`, id, dt, haz, na_is_zero)
}

